version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=orangutan_database
      - DB_USER=orangutan_admin
      - DB_PASSWORD=G@V7xh!83kR*2Jz
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=your_secret_key_here
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=orangutan_admin
      - POSTGRES_PASSWORD=G@V7xh!83kR*2Jz
      - POSTGRES_DB=orangutan_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orangutan_admin -d orangutan_database"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
